// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfxdGp6S9qTXZYt42HLW20DT1S5pR4mQM',
    appId: '1:237222768882:web:cd94cdfc65ead879aa606b',
    messagingSenderId: '237222768882',
    projectId: 'flutter-deeplearning-pro-bced7',
    authDomain: 'flutter-deeplearning-pro-bced7.firebaseapp.com',
    storageBucket: 'flutter-deeplearning-pro-bced7.firebasestorage.app',
    measurementId: 'G-376PXMSG7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf2pQdSWlksqUDTFtaPPUu0wK6zcg6kAg',
    appId: '1:237222768882:android:c1eb8ae94bde279baa606b',
    messagingSenderId: '237222768882',
    projectId: 'flutter-deeplearning-pro-bced7',
    storageBucket: 'flutter-deeplearning-pro-bced7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmVbOdbZib9mRjvQw-V0eKtcmfEHTIneY',
    appId: '1:237222768882:ios:603d3cfe1a79e49baa606b',
    messagingSenderId: '237222768882',
    projectId: 'flutter-deeplearning-pro-bced7',
    storageBucket: 'flutter-deeplearning-pro-bced7.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeeplearningProjet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBmVbOdbZib9mRjvQw-V0eKtcmfEHTIneY',
    appId: '1:237222768882:ios:603d3cfe1a79e49baa606b',
    messagingSenderId: '237222768882',
    projectId: 'flutter-deeplearning-pro-bced7',
    storageBucket: 'flutter-deeplearning-pro-bced7.firebasestorage.app',
    iosBundleId: 'com.example.flutterDeeplearningProjet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfxdGp6S9qTXZYt42HLW20DT1S5pR4mQM',
    appId: '1:237222768882:web:1c73a8c66d011736aa606b',
    messagingSenderId: '237222768882',
    projectId: 'flutter-deeplearning-pro-bced7',
    authDomain: 'flutter-deeplearning-pro-bced7.firebaseapp.com',
    storageBucket: 'flutter-deeplearning-pro-bced7.firebasestorage.app',
    measurementId: 'G-74TRCWMVWR',
  );
}
